# Generated by Django 4.0 on 2022-04-09 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_posts_options_alter_posts_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='tag',
            new_name='tagline',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='date',
        ),
        migrations.AddField(
            model_name='posts',
            name='mod_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='posts',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
