# Generated by Django 4.0 on 2022-04-10 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_tag_posts_tagline_remove_posts_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='mod_date',
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
