# Generated by Django 4.0 on 2022-04-17 16:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_posts_mod_date_alter_posts_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image_name',
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(blank=b'I00\n', on_delete=django.db.models.deletion.CASCADE, to='blog.author'),
        ),
    ]
